[babeldoc]
debug = false
working-dir = "E:\\0JHX\\Project\\OpenSciReader\\.tmp-worker-check"
output = "E:\\0JHX\\Project\\OpenSciReader\\.tmp-worker-check"
lang-in = "en"
lang-out = "zh-CN"
only-include-translated-page = false
no-dual = false
no-mono = false
report-interval = 0.25
max-pages-per-part = 0
qps = 1
pool-max-workers = 1
term-pool-max-workers = 1
min-text-length = 5
watermark-output-mode = "no_watermark"
openai-compatible-model = "deepseek-v3.2"
openai-compatible-base-url = "https://api.xinr.de/v1"
openai-compatible-api-key = "sk-t4o0oWGuyUYPSFq791sLZHjsU2sbY2qcTCeadaXSGGj3jsmg"
