// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskWorkspaceAgent(arg1) {
  return window['go']['main']['App']['AskWorkspaceAgent'](arg1);
}

export function CancelPDFTranslate(arg1) {
  return window['go']['main']['App']['CancelPDFTranslate'](arg1);
}

export function CancelWorkspaceWikiScan(arg1) {
  return window['go']['main']['App']['CancelWorkspaceWikiScan'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function CreateWorkspaceAgentSession(arg1) {
  return window['go']['main']['App']['CreateWorkspaceAgentSession'](arg1);
}

export function DeleteChatHistory(arg1) {
  return window['go']['main']['App']['DeleteChatHistory'](arg1);
}

export function DeleteDocument(arg1, arg2) {
  return window['go']['main']['App']['DeleteDocument'](arg1, arg2);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeletePDFTranslateJob(arg1) {
  return window['go']['main']['App']['DeletePDFTranslateJob'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteWorkspaceWikiPages(arg1) {
  return window['go']['main']['App']['DeleteWorkspaceWikiPages'](arg1);
}

export function DeleteWorkspaceWikiScanJob(arg1) {
  return window['go']['main']['App']['DeleteWorkspaceWikiScanJob'](arg1);
}

export function ExtractPDFMarkdown(arg1) {
  return window['go']['main']['App']['ExtractPDFMarkdown'](arg1);
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['App']['FetchProviderModels'](arg1);
}

export function GenerateResearchFigure(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateResearchFigure'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAIWorkspaceConfig(arg1) {
  return window['go']['main']['App']['GetAIWorkspaceConfig'](arg1);
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function GetConfigSnapshot() {
  return window['go']['main']['App']['GetConfigSnapshot']();
}

export function GetItemsByCollection(arg1) {
  return window['go']['main']['App']['GetItemsByCollection'](arg1);
}

export function GetPDFTranslateRuntimeStatus() {
  return window['go']['main']['App']['GetPDFTranslateRuntimeStatus']();
}

export function GetPDFTranslateStatus(arg1) {
  return window['go']['main']['App']['GetPDFTranslateStatus'](arg1);
}

export function GetWorkspaceKnowledgeCompileSummary(arg1) {
  return window['go']['main']['App']['GetWorkspaceKnowledgeCompileSummary'](arg1);
}

export function GetWorkspaceWikiPage(arg1) {
  return window['go']['main']['App']['GetWorkspaceWikiPage'](arg1);
}

export function GetWorkspaceWikiScanJob(arg1) {
  return window['go']['main']['App']['GetWorkspaceWikiScanJob'](arg1);
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function ImportPDFTranslateRuntime(arg1) {
  return window['go']['main']['App']['ImportPDFTranslateRuntime'](arg1);
}

export function ImportZoteroItem(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportZoteroItem'](arg1, arg2, arg3, arg4, arg5);
}

export function ListChatHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListChatHistory'](arg1, arg2, arg3);
}

export function ListDocuments(arg1) {
  return window['go']['main']['App']['ListDocuments'](arg1);
}

export function ListPDFTranslateJobs() {
  return window['go']['main']['App']['ListPDFTranslateJobs']();
}

export function ListReaderNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListReaderNotes'](arg1, arg2, arg3);
}

export function ListWorkspaceAgentMessages(arg1) {
  return window['go']['main']['App']['ListWorkspaceAgentMessages'](arg1);
}

export function ListWorkspaceAgentMessagesForWorkspace(arg1, arg2) {
  return window['go']['main']['App']['ListWorkspaceAgentMessagesForWorkspace'](arg1, arg2);
}

export function ListWorkspaceAgentSessions(arg1) {
  return window['go']['main']['App']['ListWorkspaceAgentSessions'](arg1);
}

export function ListWorkspaceAgentSkills() {
  return window['go']['main']['App']['ListWorkspaceAgentSkills']();
}

export function ListWorkspaceKnowledgeSources(arg1) {
  return window['go']['main']['App']['ListWorkspaceKnowledgeSources'](arg1);
}

export function ListWorkspaceWikiPages(arg1) {
  return window['go']['main']['App']['ListWorkspaceWikiPages'](arg1);
}

export function ListWorkspaceWikiScanJobs() {
  return window['go']['main']['App']['ListWorkspaceWikiScanJobs']();
}

export function ListWorkspaces() {
  return window['go']['main']['App']['ListWorkspaces']();
}

export function LoadPDFDocument(arg1) {
  return window['go']['main']['App']['LoadPDFDocument'](arg1);
}

export function ProxyTranslation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProxyTranslation'](arg1, arg2, arg3, arg4, arg5);
}

export function RemovePDFTranslateRuntime() {
  return window['go']['main']['App']['RemovePDFTranslateRuntime']();
}

export function ResolvePDFPath(arg1) {
  return window['go']['main']['App']['ResolvePDFPath'](arg1);
}

export function SaveAIWorkspaceConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveAIWorkspaceConfig'](arg1, arg2);
}

export function SaveChatHistory(arg1) {
  return window['go']['main']['App']['SaveChatHistory'](arg1);
}

export function SaveModel(arg1) {
  return window['go']['main']['App']['SaveModel'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveReaderNote(arg1) {
  return window['go']['main']['App']['SaveReaderNote'](arg1);
}

export function SelectImportFiles() {
  return window['go']['main']['App']['SelectImportFiles']();
}

export function SelectPDFTranslateRuntimePackage() {
  return window['go']['main']['App']['SelectPDFTranslateRuntimePackage']();
}

export function StartPDFTranslate(arg1) {
  return window['go']['main']['App']['StartPDFTranslate'](arg1);
}

export function StartWorkspaceWikiScan(arg1) {
  return window['go']['main']['App']['StartWorkspaceWikiScan'](arg1);
}

export function StreamLLMChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StreamLLMChat'](arg1, arg2, arg3, arg4);
}
