// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPDFTranslate(arg1) {
  return window['go']['main']['App']['CancelPDFTranslate'](arg1);
}

export function DeleteChatHistory(arg1) {
  return window['go']['main']['App']['DeleteChatHistory'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeletePDFTranslateJob(arg1) {
  return window['go']['main']['App']['DeletePDFTranslateJob'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function FetchProviderModels(arg1) {
  return window['go']['main']['App']['FetchProviderModels'](arg1);
}

export function GenerateResearchFigure(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateResearchFigure'](arg1, arg2, arg3, arg4);
}

export function GetAIWorkspaceConfig() {
  return window['go']['main']['App']['GetAIWorkspaceConfig']();
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function GetConfigSnapshot() {
  return window['go']['main']['App']['GetConfigSnapshot']();
}

export function GetItemsByCollection(arg1) {
  return window['go']['main']['App']['GetItemsByCollection'](arg1);
}

export function GetPDFTranslateRuntimeStatus() {
  return window['go']['main']['App']['GetPDFTranslateRuntimeStatus']();
}

export function GetPDFTranslateStatus(arg1) {
  return window['go']['main']['App']['GetPDFTranslateStatus'](arg1);
}

export function ImportPDFTranslateRuntime(arg1) {
  return window['go']['main']['App']['ImportPDFTranslateRuntime'](arg1);
}

export function ListChatHistory(arg1) {
  return window['go']['main']['App']['ListChatHistory'](arg1);
}

export function ListPDFTranslateJobs() {
  return window['go']['main']['App']['ListPDFTranslateJobs']();
}

export function ListReaderNotes(arg1) {
  return window['go']['main']['App']['ListReaderNotes'](arg1);
}

export function LoadPDFDocument(arg1) {
  return window['go']['main']['App']['LoadPDFDocument'](arg1);
}

export function ProxyTranslation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProxyTranslation'](arg1, arg2, arg3, arg4, arg5);
}

export function RemovePDFTranslateRuntime() {
  return window['go']['main']['App']['RemovePDFTranslateRuntime']();
}

export function ResolvePDFPath(arg1) {
  return window['go']['main']['App']['ResolvePDFPath'](arg1);
}

export function SaveAIWorkspaceConfig(arg1) {
  return window['go']['main']['App']['SaveAIWorkspaceConfig'](arg1);
}

export function SaveChatHistory(arg1) {
  return window['go']['main']['App']['SaveChatHistory'](arg1);
}

export function SaveModel(arg1) {
  return window['go']['main']['App']['SaveModel'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveReaderNote(arg1) {
  return window['go']['main']['App']['SaveReaderNote'](arg1);
}

export function SelectPDFTranslateRuntimePackage() {
  return window['go']['main']['App']['SelectPDFTranslateRuntimePackage']();
}

export function StartPDFTranslate(arg1) {
  return window['go']['main']['App']['StartPDFTranslate'](arg1);
}

export function StreamLLMChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StreamLLMChat'](arg1, arg2, arg3, arg4);
}
