// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {translator} from '../models';
import {main} from '../models';

export function CancelPDFTranslate(arg1:string):Promise<translator.JobSnapshot>;

export function DeleteChatHistory(arg1:number):Promise<void>;

export function DeleteModel(arg1:number):Promise<void>;

export function DeletePDFTranslateJob(arg1:string):Promise<void>;

export function DeleteProvider(arg1:number):Promise<void>;

export function FetchProviderModels(arg1:number):Promise<main.DiscoveredModelsResponse>;

export function GenerateResearchFigure(arg1:number,arg2:number,arg3:string,arg4:main.GatewayContextData):Promise<main.FigureGenerationResult>;

export function GetAIWorkspaceConfig():Promise<main.AIWorkspaceConfig>;

export function GetCollections(arg1:string):Promise<Array<main.CollectionTree>>;

export function GetConfigSnapshot():Promise<main.ConfigSnapshot>;

export function GetItemsByCollection(arg1:string):Promise<Array<main.ZoteroItem>>;

export function GetPDFTranslateStatus(arg1:string):Promise<translator.JobSnapshot>;

export function ListChatHistory(arg1:string):Promise<Array<main.ChatHistoryEntry>>;

export function ListPDFTranslateJobs():Promise<Array<translator.JobSnapshot>>;

export function ListReaderNotes(arg1:string):Promise<Array<main.ReaderNoteEntry>>;

export function LoadPDFDocument(arg1:string):Promise<main.PDFDocumentPayload>;

export function ProxyTranslation(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ResolvePDFPath(arg1:string):Promise<string>;

export function SaveAIWorkspaceConfig(arg1:main.AIWorkspaceConfig):Promise<main.AIWorkspaceConfig>;

export function SaveChatHistory(arg1:main.ChatHistoryEntry):Promise<main.ChatHistoryEntry>;

export function SaveModel(arg1:main.ModelUpsertInput):Promise<main.ModelRecord>;

export function SaveProvider(arg1:main.ProviderUpsertInput):Promise<main.ProviderRecord>;

export function SaveReaderNote(arg1:main.ReaderNoteEntry):Promise<main.ReaderNoteEntry>;

export function StartPDFTranslate(arg1:main.PDFTranslateStartInput):Promise<translator.JobSnapshot>;

export function StreamLLMChat(arg1:number,arg2:number,arg3:string,arg4:main.GatewayContextData):Promise<string>;
