// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {translator} from '../models';

export function AskWorkspaceAgent(arg1:main.WorkspaceAgentAskInput):Promise<main.WorkspaceAgentAskResult>;

export function CancelPDFTranslate(arg1:string):Promise<translator.JobSnapshot>;

export function CancelWorkspaceWikiScan(arg1:string):Promise<main.WorkspaceWikiScanJob>;

export function CreateWorkspace(arg1:main.WorkspaceUpsertInput):Promise<main.Workspace>;

export function CreateWorkspaceAgentSession(arg1:main.WorkspaceAgentSessionCreateInput):Promise<main.WorkspaceAgentSession>;

export function DeleteChatHistory(arg1:number):Promise<void>;

export function DeleteDocument(arg1:string,arg2:string):Promise<void>;

export function DeleteModel(arg1:number):Promise<void>;

export function DeletePDFTranslateJob(arg1:string):Promise<void>;

export function DeleteProvider(arg1:number):Promise<void>;

export function DeleteWorkspaceWikiPages(arg1:string):Promise<void>;

export function DeleteWorkspaceWikiScanJob(arg1:string):Promise<void>;

export function ExtractPDFMarkdown(arg1:string):Promise<main.PDFMarkdownPayload>;

export function FetchProviderModels(arg1:number):Promise<main.DiscoveredModelsResponse>;

export function GenerateResearchFigure(arg1:number,arg2:number,arg3:string,arg4:main.GatewayContextData,arg5:string):Promise<main.FigureGenerationResult>;

export function GetAIWorkspaceConfig(arg1:string):Promise<main.AIWorkspaceConfig>;

export function GetCollections(arg1:string):Promise<Array<main.CollectionTree>>;

export function GetConfigSnapshot():Promise<main.ConfigSnapshot>;

export function GetItemsByCollection(arg1:string):Promise<Array<main.ZoteroItem>>;

export function GetPDFTranslateRuntimeStatus():Promise<main.PDFTranslateRuntimeConfig>;

export function GetPDFTranslateStatus(arg1:string):Promise<translator.JobSnapshot>;

export function GetWorkspaceKnowledgeCompileSummary(arg1:string):Promise<main.WorkspaceKnowledgeCompileSummary>;

export function GetWorkspaceWikiPage(arg1:string):Promise<main.WorkspaceWikiPageContent>;

export function GetWorkspaceWikiScanJob(arg1:string):Promise<main.WorkspaceWikiScanJob>;

export function ImportFiles(arg1:main.ImportFilesInput):Promise<main.ImportFilesResult>;

export function ImportPDFTranslateRuntime(arg1:string):Promise<main.PDFTranslateRuntimeImportResult>;

export function ImportZoteroItem(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ImportFilesResult>;

export function ListChatHistory(arg1:string,arg2:string,arg3:string):Promise<Array<main.ChatHistoryEntry>>;

export function ListDocuments(arg1:string):Promise<Array<main.DocumentRecord>>;

export function ListPDFTranslateJobs():Promise<Array<translator.JobSnapshot>>;

export function ListReaderNotes(arg1:string,arg2:string,arg3:string):Promise<Array<main.ReaderNoteEntry>>;

export function ListWorkspaceAgentMessages(arg1:string):Promise<Array<main.WorkspaceAgentMessage>>;

export function ListWorkspaceAgentMessagesForWorkspace(arg1:string,arg2:string):Promise<Array<main.WorkspaceAgentMessage>>;

export function ListWorkspaceAgentSessions(arg1:string):Promise<Array<main.WorkspaceAgentSession>>;

export function ListWorkspaceKnowledgeSources(arg1:string):Promise<Array<main.WorkspaceKnowledgeSource>>;

export function ListWorkspaceWikiPages(arg1:string):Promise<Array<main.WorkspaceWikiPage>>;

export function ListWorkspaceWikiScanJobs():Promise<Array<main.WorkspaceWikiScanJob>>;

export function ListWorkspaces():Promise<Array<main.Workspace>>;

export function LoadPDFDocument(arg1:string):Promise<main.PDFDocumentPayload>;

export function ProxyTranslation(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string>;

export function RemovePDFTranslateRuntime():Promise<void>;

export function ResolvePDFPath(arg1:string):Promise<string>;

export function SaveAIWorkspaceConfig(arg1:string,arg2:main.AIWorkspaceConfig):Promise<main.AIWorkspaceConfig>;

export function SaveChatHistory(arg1:main.ChatHistoryEntry):Promise<main.ChatHistoryEntry>;

export function SaveModel(arg1:main.ModelUpsertInput):Promise<main.ModelRecord>;

export function SaveProvider(arg1:main.ProviderUpsertInput):Promise<main.ProviderRecord>;

export function SaveReaderNote(arg1:main.ReaderNoteEntry):Promise<main.ReaderNoteEntry>;

export function SelectImportFiles():Promise<Array<string>>;

export function SelectPDFTranslateRuntimePackage():Promise<string>;

export function StartPDFTranslate(arg1:main.PDFTranslateStartInput):Promise<translator.JobSnapshot>;

export function StartWorkspaceWikiScan(arg1:main.WorkspaceWikiScanStartInput):Promise<main.WorkspaceWikiScanJob>;

export function StreamLLMChat(arg1:number,arg2:number,arg3:string,arg4:main.GatewayContextData):Promise<string>;
